language: node_js
cache:
  directories:
    - node_modules
env:
  - global:
      - CODECOV_TOKEN: c2a929f8-91d9-476d-87ae-d0a2aca1b055
node_js:
  - "node"
  - "10"

before_install:
  - npm i

script:
  - nyc npm test && nyc report --reporter=text-lconv > coverage.lcov && codecov

dist: xenial
