name: Build local version

on:
  push:
    branches:
      - typescript
    paths:
      - 'package.json'
      - 'src/**'
      - 'public/**'

jobs:
  build:
    if: github.repository == 'ryalee2014/CUP-Online-Judge-NG-FrontEnd'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Use Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build local distribution
        run: |
          npm i
          npm run modern:local

      - name: Checkout repository to store local distribution
        uses: actions/checkout@v2
        with:
          repository: ryanlee2014/CUP-Online-Judge-Frontend-Local
          path: local_build
          persist-credential: false
          fetch-depth: 0

      - name: Move file to repository
        run: cp -r dist/* local_build/

      - name: Commit file and push
        run: |
          cd local_build
          git config --local user.email "gxlhybh@gmail.com"
          git config --local user.name "Ryan Lee"
          git add --all
          git commit -m "deploy `TZ=UTF-8 date +'%Y-%m-%d %H:%M:%S'`"
          git tag "v`cat VERSION`"
          git push -f https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-Frontend-Local
          git push --tags https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-Frontend-Local

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
