name: Build local version

on:
  push:
    branches:
      - typescript
    paths:
      - 'package.json'
      - 'src/**'
      - 'public/**'
      - '.github/**'
      - 'vue.config.js'

jobs:
  build:
    if: github.repository == 'ryanlee2014/CUP-Online-Judge-Frontend'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Use Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build local distribution
        run: |
          npm i
          npm run modern:local

      - name: Checkout repository to store local distribution
        run: |
          git clone https://github.com/ryanlee2014/CUP-Online-Judge-Frontend-Local.git local_build

      - name: Move file to repository
        run: |
          rm -rf local_build/*
          cp -r dist/* local_build/

      - name: Commit files and push
        run: |
          cd local_build
          git config --local user.email "gxlhybh@gmail.com"
          git config --local user.name "Ryan Lee"
          git add --all
          git commit -m "deploy `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
          git tag "v`cat VERSION`"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          repository: ryanlee2014/CUP-Online-Judge-Frontend-Local
          force: true
          directory: local_build
          tags: true
