name: Publish releases to CDN repository

on:
  push:
    branches:
      - typescript

jobs:
  publish:
    if: github.repository == 'ryanlee2014/CUP-Online-Judge-NG-FrontEnd'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/checkout@v2
        name: Checkout CDN Repository
        with:
          repository: ryanlee2014/CUP-Online-Judge-CDN
          path: cdn
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Move file to another repository
        run: cp -r dist/* cdn/
      - name: Commit files and push
        run: |
          cd cdn
          git config --local user.email "gxlhybh@gmail.com"
          git config --local user.name "Ryan Lee"
          git add --all
          git commit -m "deploy `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
          git tag "v`cat VERSION`"
          git push -f https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-CDN.git master
          git push --tags https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-CDN.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
