name: Publish releases to CDN repository

on:
  push:
    branches:
      - typescript
    paths:
      - 'package.json'
      - 'src/**'
      - 'public/**'
      - 'vue.config.js'

jobs:
  publish:
    if: github.repository == 'ryanlee2014/CUP-Online-Judge-NG-FrontEnd'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build env
        run: |
          echo "::set-env name=NEED_BUILD::$(cat NEED_BUILD)"

      - name: Use Node.js environment
        if: env.NEED_BUILD == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build distribution if needed
        if: env.NEED_BUILD == 'true'
        run: |
          npm i
          npm run modern

      - name: Update dist folder to current repository
        if: env.NEED_BUILD == 'true'
        run: |
          git config --local user.email "gxlhybh@gmail.com"
          git config --local user.name "Ryan Lee"
          git add dist
          git commit -m "Auto commit version $(cat public/VERSION)"
          git push -f https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-NG-FrontEnd.git typescript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}


      - uses: actions/checkout@v2
        name: Checkout CDN Repository
        with:
          repository: ryanlee2014/CUP-Online-Judge-CDN
          path: cdn
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Move file to another repository
        run: cp -r dist/* cdn/


      - name: Commit files and push
        run: |
          cd cdn
          git config --local user.email "gxlhybh@gmail.com"
          git config --local user.name "Ryan Lee"
          git add --all
          git commit -m "deploy `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
          git tag "v`cat VERSION`"
          git push -f https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-CDN.git master
          git push --tags https://ryanlee2014:$GITHUB_TOKEN@github.com/ryanlee2014/CUP-Online-Judge-CDN.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
